version: '3'
services:
  db:
    container_name: test_db
    image: postgres:13-alpine
    environment:
      - PGPASSWORD=test
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_ROOT_PASSWORD=test
    ports:
      - '5433:5432'
    networks:
      dev:
  api:
    container_name: test_api
    image: testapi:latest
    build: api
    volumes:
      - ./api:/var/www/html
    ports:
      - "80:80"
    expose:
      - '80'
    depends_on:
      - db
    networks:
      dev:
  app:
    container_name: test_frontend
    build: frontend
    user: "node"
    environment:
      - NODE_ENV=development
      - NUXT_HOST=0.0.0.0
    volumes:
      - ./frontend:/app
    command: sh -c "yarn install && yarn dev"
    ports:
      - 3000:3000
    depends_on:
        - db
        - api
networks:
  dev:
    driver: bridge
